# -*- coding: utf-8 -*-
"""File 4- data_generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-Ek_KxRpKx_-YSJfsvki5KHyFWNi18Z
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

# Seed for reproducibility
np.random.seed(42)
random.seed(42)

num_patients = 2000
num_encounters = 10000

print("Generating clinical lookup profiles...")

# 1. Dim_Departments
depts = [
    {"DepartmentID": 1, "DepartmentName": "Emergency Room", "TotalBeds": 45, "ICU_Flag": "N"},
    {"DepartmentID": 2, "DepartmentName": "Intensive Care Unit", "TotalBeds": 20, "ICU_Flag": "Y"},
    {"DepartmentID": 3, "DepartmentName": "General Medicine", "TotalBeds": 120, "ICU_Flag": "N"},
    {"DepartmentID": 4, "DepartmentName": "Cardiology", "TotalBeds": 35, "ICU_Flag": "N"},
    {"DepartmentID": 5, "DepartmentName": "Pediatrics", "TotalBeds": 25, "ICU_Flag": "N"}
]
df_depts = pd.DataFrame(depts)

# 2. Dim_Providers
specialties = ["Emergency Medicine", "Critical Care", "Internal Medicine", "Cardiology", "Pediatrics"]
first_names = ["James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", "William", "Elizabeth"]
last_names = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez"]

providers = []
for i in range(1, 51):
    providers.append({
        "ProviderID": i,
        "NPI": str(random.randint(1000000000, 1999999999)),
        "FirstName": random.choice(first_names),
        "LastName": random.choice(last_names),
        "Specialty": random.choice(specialties),
        "StaffStatus": "Active"
    })
df_providers = pd.DataFrame(providers)

# 3. Dim_Patients (With targeted anomalies)
patients = []
for i in range(1, num_patients + 1):
    fn = random.choice(first_names)
    ln = random.choice(last_names)
    dob = datetime(1950, 1, 1) + timedelta(days=random.randint(0, 25000))
    gender = random.choice(["Male", "Female", "M", "F", None]) # Dirty categorical strings
    zip_code = str(random.randint(10000, 99999))

    patients.append({
        "PatientID": i,
        "MRN": f"MRN-{i:06d}",
        "FirstName": fn,
        "LastName": ln,
        "DateOfBirth": dob.strftime('%Y-%m-%d'),
        "Gender": gender,
        "ZipCode": zip_code
    })

# Force explicitly duplicated data rows for cleaning phase practice
for _ in range(50):
    dup = random.choice(patients).copy()
    dup["PatientID"] = len(patients) + 1
    # Introduce lowercase discrepancy variants
    dup["FirstName"] = dup["FirstName"].lower()
    patients.append(dup)

df_patients = pd.DataFrame(patients)

# 4. Fact_Encounters, Bed Movements, Billing
encounters = []
movements = []
billing = []
icd10_codes = ["I21.9", "J18.9", "E11.9", "A41.9", "N39.0", "I50.9"]
dispositions = ["Home", "Transferred to Skilled Nursing Facility", "Deceased", "Left Against Medical Advice"]

start_date = datetime(2024, 1, 1)
mov_counter = 1
tx_counter = 1

for i in range(1, num_encounters + 1):
    p_id = random.randint(1, len(df_patients))
    prov_id = random.randint(1, 50)
    dept_id = random.randint(1, 5)
    admit_type = random.choice(["Emergency", "Urgent", "Elective"])

    admit_dt = start_date + timedelta(days=random.randint(0, 730), hours=random.randint(0, 23), minutes=random.randint(0, 59))

    # Introduce chronological logical anomaly row vectors (Discharge before Admission)
    if random.random() < 0.02:
        discharge_dt = admit_dt - timedelta(hours=random.randint(1, 24))
    else:
        discharge_dt = admit_dt + timedelta(days=random.randint(0, 14), hours=random.randint(1, 23))

    # Open encounter simulation (Patient not yet discharged)
    if random.random() < 0.03:
        discharge_dt = None

    encounters.append({
        "EncounterID": i,
        "PatientID": p_id,
        "PrimaryProviderID": prov_id,
        "AdmitDepartmentID": dept_id,
        "AdmissionType": admit_type,
        "AdmitDateTime": admit_dt.strftime('%Y-%m-%d %H:%M:%S'),
        "DischargeDateTime": discharge_dt.strftime('%Y-%m-%d %H:%M:%S') if discharge_dt else None,
        "PrimaryDiagnosisCode": random.choice(icd10_codes),
        "DischargeDisposition": random.choice(dispositions) if discharge_dt else None
    })

    # Bed movements logic generation
    current_time = admit_dt
    if discharge_dt:
        while current_time < discharge_dt:
            stay_duration = timedelta(days=random.randint(1, 3), hours=random.randint(0, 12))
            end_time = current_time + stay_duration
            if end_time > discharge_dt:
                end_time = discharge_dt

            movements.append({
                "MovementID": mov_counter,
                "EncounterID": i,
                "PatientID": p_id,
                "DepartmentID": random.randint(1, 5),
                "BedNumber": f"B-{random.randint(100, 299)}",
                "StartDateTime": current_time.strftime('%Y-%m-%d %H:%M:%S'),
                "EndDateTime": end_time.strftime('%Y-%m-%d %H:%M:%S')
            })
            mov_counter += 1
            current_time = end_time

    # Financial transactions generation
    if discharge_dt:
        charges = round(random.uniform(500.00, 15000.00), 2)
        ins_paid = round(charges * random.choice([0.0, 0.5, 0.8]), 2)
        pat_paid = round((charges - ins_paid) * random.choice([0.0, 0.5, 1.0]), 2)

        # Calculate total payments first to avoid the walrus operator syntax conflict
        total_paid = ins_paid + pat_paid
        adj = round(charges - total_paid, 2) if total_paid < charges else 0.0

        billing.append({
            "TxID": tx_counter,
            "EncounterID": i,
            "PatientID": p_id,
            "TransactionDate": discharge_dt.strftime('%Y-%m-%d'),
            "ChargeAmount": charges,
            "InsurancePaid": ins_paid,
            "PatientPaid": pat_paid,
            "AdjustmentAmount": adj
        })
        tx_counter += 1

df_depts = pd.DataFrame(depts)
df_providers = pd.DataFrame(providers)
df_patients = pd.DataFrame(patients)
df_encounters = pd.DataFrame(encounters)
df_movements = pd.DataFrame(movements)
df_billing = pd.DataFrame(billing)

# Save to system storage path structures
df_depts.to_csv('dim_departments.csv', index=False)
df_providers.to_csv('dim_providers.csv', index=False)
df_patients.to_csv('dim_patients.csv', index=False)
df_encounters.to_csv('fact_encounters.csv', index=False)
df_movements.to_csv('fact_bed_movements.csv', index=False)
df_billing.to_csv('fact_billing_transactions.csv', index=False)

print("Data generation complete. 6 files outputted successfully.")